import sys

def trovaGeneratori(n: int) -> list[int]:
    all_numbers = {i for i in range(1, n)} # used to check if all numbers are generated
    generators = [] # list that will contain all the generators
    for i in range(1, n):
        elements = set() # keep track of all elements generated by the current number
        curr_element = i
        elements.add(curr_element)
        for _ in range(1000):
            curr_element = (curr_element + i) % n
            elements.add(curr_element)
            if curr_element == 0: break
        diff = all_numbers.difference(elements)
        if diff == set():
            generators.append(i)
    return generators

def main():
    args = sys.argv

    if len(args) < 2:
        print(f"Usage: python generatoriGruppo.py n")
        exit(1)
    
    n: int = 0
    try:
        n = int(args[1])
    except ValueError as e:
        print(f"Errore: {e}")
        exit(1)

    gen = trovaGeneratori(n)
    print(f"{len(gen)} generatori: \n {gen}")

if __name__ == "__main__":
    main()